### ISSUE TITLE
Ping? Pong! - Health check via TCP

### ISSUE THREAD

**Issue by andryyy** [HeinleinSupport/olefy#7]
Feature request for a little "ping? pong!" event via TCP to check if olefy is still alive.

**Comment by andryyy** [comment]
Merci!

**Comment by andryyy** [comment]
I think I miss something here:

```
olefy-mailcow_1      | olefy INFO eof_received <> 4 bytes (stream size)
olefy-mailcow_1      | olefy ERROR eof_received <> Protocol ERROR: no OLEFY/1.0 found
olefy-mailcow_1      | olefy INFO eof_received <> ('172.22.1.8', 57346) response send: b'[ { "error": "Protocol error" } ]'
```

I tried a simple PING, but also tried with the protocol + PING and protocol, header + PING. It never PONGS me back. :)

**Comment by c-rosenberg** [comment]
Sorry. c&p error

`echo PING|nc -q1 127.0.0.1 10050     
                                                                                                                                                      
PONG#`

**Comment by andryyy** [comment]
Thanks!
